on:
  schedule:
  ## - cron:  "*/15 * * * *"
  - cron:  "0 0 * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "ows-ali/Hacktoberfest"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
